### PR TITLE
Improved Automation tests on Operator, pipeline spec

### PR DESCRIPTION
**Pull request by praveen4g0**
- Operator installation by subscribing to canary channel on real cluster.
- Operator deletion from cluster
- Creating simple pipeline and run pipeline using tkn client

Assumptions: 
-  latest `oc` binary should be installed.
-  latest `tkn` binary which is compatible with operator should be installed.

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@praveen4g0 could you push the vendor files in a different pr.
This pr is huge and my browser is hanging when i try to review it.

**Comment by praveen4g0** [comment]
@nikhil-thomas I have deleted ```vendor``` file and updated the PR :)

**Comment by nikhil-thomas** [comment]
@praveen4g0 i see that this pr wants to merge  `praveen4g0:master` is that intended.

i highly recommend naming the branch with a name hinting the intention/type of this patch.

**Comment by praveen4g0** [comment]
I have raised new PR https://github.com/openshift-pipelines/release-tests/pull/6, with new branch for Automation scripts ```praveen4g0:release-automation```

**Pull request closed without merging**
