### PR TITLE
Added pipelines/Task tests under spec

### PR DESCRIPTION
**Pull request by praveen4g0**
- Added Task tests under spec section
- Added simple Pipeline tests under spec section

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@praveen4g0 could you push the `vendor` files in a different pr.
This pr is huge and my browser is hanging when i try to review it.

**Comment by praveen4g0** [comment]
@nikhil-thomas There are no ```vendor``` files in this PR, This includes only an additional Tests of task under spec section, ```vendor``` files I have pushed into another pr (https://github.com/openshift-pipelines/release-tests/pull/4)

**Comment by nikhil-thomas** [comment]
my bad, the comment was for the other pr, let me post it there
https://github.com/openshift-pipelines/release-tests/pull/4#issuecomment-569868867

**Comment by praveen4g0** [comment]
Will be raising new PR, by adding new specs using gauge framework

**Pull request closed without merging**
