### PR TITLE
tektonhub e2e tests without Authentication

### PR DESCRIPTION
**Pull request by manojbison**

### CODE REVIEW

**Comment by manojbison** [comment]
```
manoj@Manojs-MacBook-Pro release-tests % gauge run --env "default, test" --log-level=debug --verbose specs/hub/hub.spec
gauge run specs/hub/hub.spec
env : [default, test]
log-level : [debug]
verbose : [true]
env will be loaded from default directory 'env'
'gauge_environment' set to 'default'
env will be loaded from default directory 'env'
'gauge_environment' set to 'test'
Created gauge_screenshots_dir at /Users/manoj/Desktop/release-tests/.gauge/screenshots
Plugin go is already installed.
Plugin html-report is already installed.
Plugin xml-report is already installed.
Parsing started.
Started concepts parsing.
14 concepts parsing completed.
Started specifications parsing.
1 specifications parsing completed.
Parsing completed.
Starting go runner
Checking updates...
Downloading https://downloads.gauge.org/plugin/go?l=go&p=go,html-report,python,screenshot,xml-report&o=darwin&a=amd64
Downloading https://downloads.gauge.org/plugin/html-report?l=go&p=go,html-report,python,screenshot,xml-report&o=darwin&a=amd64
Downloading https://downloads.gauge.org/plugin/python?l=go&p=go,html-report,python,screenshot,xml-report&o=darwin&a=amd64
Downloading https://downloads.gauge.org/plugin/screenshot?l=go&p=go,html-report,python,screenshot,xml-report&o=darwin&a=amd64
Downloading https://downloads.gauge.org/plugin/xml-report?l=go&p=go,html-report,python,screenshot,xml-report&o=darwin&a=amd64
Established connection to runner.
Validation started.
Validation completed.
Run started
Starting Html Report plugin
Setting MaxRecvMsgSize = 1024 MB
Attempting to connect to grpc server at port: 64234
Successfully made the connection with plugin with port: 64234
Starting Xml Report plugin
Attempting to connect to grpc server at port: 64239
Successfully made the connection with plugin with port: 64239
Initialising suite data store.
# HUB tests tests
  ## Install HUB without authentication: PIPELINES-21-TC01
2023/03/23 20:12:05 output: Now using project "releasetest-5bdzj" on server "https://api.test1.pli43-tt4.psi.ospqa.com:6443".
You can add applications to this project with the 'new-app' command. For example, try:
oc new-app rails-postgresql-example
to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:
kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname
2023/03/23 20:12:05 Verify SA "pipeline" is created in namespace "releasetest-5bdzj"
      * Verify ServiceAccount "pipeline" exist   ...[PASS]
2023/03/23 20:14:31 output: tektonhub.operator.tekton.dev/hub created
      * Create TektinHub CR      ...[PASS]
      * Verify that the hub CR is in True state  ...[PASS]
2023/03/23 20:17:39 TektonHub deployment is up and running
      * Verify that the TektonHub deployment is up and running   ...[PASS]
2023/03/23 20:17:39 TektonHub UI is accessible
      * Verify that the HUB UI is accessbile     ...[PASS]
Enumerating objects: 10430, done.
Counting objects:  42% (99/235)
Counting objects: 100% (235/235), done.
Compressing objects: 100% (184/184), done.
Total 10430 (delta 81), reused 165 (delta 42), pack-reused 10195
cloned
YAML file updated successfully!
M  task/git-clone/0.9/git-clone.yaml
e6beaa758751961365728455f1e9b995150cb9c7
https://tekton-hub-ui-openshift-pipelines.apps.pli43-tt4.psi.ospqa.com https://tekton-hub-api-openshift-pipelines.apps.pli43-tt4.psi.ospqa.com
      * Verify that the TektonHub elements like Kind, Platform, Catalog, Category are available  ...[PASS]
2023/03/23 20:17:57 output: project.project.openshift.io "releasetest-5bdzj" deleted

Transformed SuiteResult to report structure
Successfully generated html-report to => /Users/manoj/Desktop/release-tests/reports/html-report/index.html

Done generating HTML report using theme from /Users/manoj/.gauge/plugins/html-report/4.2.0/themes/default
Successfully generated xml-report to => /Users/manoj/Desktop/release-tests/reports/xml-report

Sending kill message to Html Report plugin.
Sending kill message to Xml Report plugin.
Sending kill message to runner.
ok      command-line-arguments  355.650s
Runner with PID:78673 has exited
Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      1 executed      1 passed        0 failed        0 skipped

Total time taken: 5m54.115s
Updates are available. Run `gauge update -c` for more info.

**Review by ppitonak — CHANGES_REQUESTED** [review]
Please rebase it because it's a mess right now due to changes in master branch.

**Comment by ppitonak** [comment]
We should probably create a simple catalog in `github.com/openshift-pipelines/test-catalog` which would only contain one or two tasks, e.g. something like https://github.com/ppitonak/tektoncd-catalog/blob/ppitonak/task/echo/0.1/echo.yaml

**Comment by manojbison** [comment]
@ppitonak done with the rebase changes

**Comment by ppitonak** [comment]
It's not rebased, see the image :( PR says that 127 files were changed, this is impossible to review. BTW, if you worked on a feature branch instead of `master`, it would be easier to rebase
release_tests_128

**Pull request closed without merging**
